UPDATE `mob_groups` SET respawntime = 3600 WHERE name = 'Mother_Globe'         AND groupid =   9;
UPDATE `mob_groups` SET respawntime = 3600 WHERE name = 'Faust'                AND groupid =   6;
UPDATE `mob_groups` SET respawntime = 3600 WHERE name = 'Zipacna'              AND groupid =  16;

UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP =    0 WHERE name = 'Mother_Globe'         AND groupid =   9;
UPDATE `mob_groups` SET minLevel =  85, maxLevel =  85, HP =      0, MP =    0 WHERE name = 'Slave_Globe'          AND groupid =  10;
UPDATE `mob_groups` SET minLevel =  85, maxLevel =  85, HP =      0, MP =    0 WHERE name = 'Slave_Globe'          AND groupid =  10;
UPDATE `mob_groups` SET minLevel =  85, maxLevel =  85, HP =      0, MP =    0 WHERE name = 'Slave_Globe'          AND groupid =  10;
UPDATE `mob_groups` SET minLevel =  85, maxLevel =  85, HP =      0, MP =    0 WHERE name = 'Slave_Globe'          AND groupid =  10;
UPDATE `mob_groups` SET minLevel =  85, maxLevel =  85, HP =      0, MP =    0 WHERE name = 'Slave_Globe'          AND groupid =  10;
UPDATE `mob_groups` SET minLevel =  85, maxLevel =  85, HP =      0, MP =    0 WHERE name = 'Slave_Globe'          AND groupid =  10;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP =    0 WHERE name = 'Steam_Cleaner'        AND groupid =  15;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP =    0 WHERE name = 'Faust'                AND groupid =   6;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP = 8500 WHERE name = 'Brigandish_Blade'     AND groupid =  14;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP =    0 WHERE name = 'Ullikummi'            AND groupid =  12;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP =    0 WHERE name = 'Despot'               AND groupid =  13;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  35000, MP = 8500 WHERE name = 'Olla_Pequena'         AND groupid =  24;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  55000, MP = 8500 WHERE name = 'Olla_Media'           AND groupid =  25;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP = 8500 WHERE name = 'Olla_Grande'          AND groupid =  26;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  75000, MP =    0 WHERE name = 'Zipacna'              AND groupid =  16;
UPDATE `mob_groups` SET minLevel = 100, maxLevel = 100, HP = 100000, MP = 8500 WHERE name = 'Seiryu'               AND groupid =  16;
UPDATE `mob_groups` SET minLevel = 100, maxLevel = 100, HP = 100000, MP = 8500 WHERE name = 'Suzaku'               AND groupid =  18;
UPDATE `mob_groups` SET minLevel = 100, maxLevel = 100, HP = 100000, MP = 8500 WHERE name = 'Byakko'               AND groupid =  17;
UPDATE `mob_groups` SET minLevel = 100, maxLevel = 100, HP = 100000, MP = 8500 WHERE name = 'Genbu'                AND groupid =  15;
UPDATE `mob_groups` SET minLevel = 105, maxLevel = 105, HP = 105000, MP = 8500 WHERE name = 'Kirin'                AND groupid =  27;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =      0, MP =    0 WHERE name = 'Kirins_Avatar'        AND groupid =  32;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP =      0, MP =    0 WHERE name = 'Genbu_pet'            AND groupid = 256;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP =      0, MP =    0 WHERE name = 'Seiryu_pet'           AND groupid = 257;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP =      0, MP =    0 WHERE name = 'Suzaku_pet'           AND groupid = 258;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP =      0, MP =    0 WHERE name = 'Byakko_pet'           AND groupid = 259;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  90000, MP =    0 WHERE name = 'Ixaern_DRG'           AND groupid =  31;
UPDATE `mob_groups` SET minLevel =  85, maxLevel =  85, HP =      0, MP =    0 WHERE name = 'Ixaern_DRGs_Wynav'    AND groupid =  32;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  90000, MP =    0 WHERE name = 'Ixaern_MNK'           AND groupid =  24;
UPDATE `mob_groups` SET minLevel =  90, maxLevel =  90, HP =  90000, MP =    0 WHERE name = 'Ixaern_DRK'           AND groupid =  28;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP = 100000, MP = 8500 WHERE name = 'Jailer_of_Fortitude'  AND groupid =  25;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP = 100000, MP = 8500 WHERE name = 'Jailer_of_Temperance' AND groupid =  23;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP = 100000, MP = 8500 WHERE name = 'Jailer_of_Faith'      AND groupid =  30;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP = 100000, MP = 8500 WHERE name = 'Jailer_of_Justice'    AND groupid =  50;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP = 100000, MP = 8500 WHERE name = 'Jailer_of_Hope'       AND groupid =  49;
UPDATE `mob_groups` SET minLevel =  95, maxLevel =  95, HP = 100000, MP = 8500 WHERE name = 'Jailer_of_Prudence'   AND groupid =  52;
UPDATE `mob_groups` SET minLevel = 105, maxLevel = 105, HP = 105000, MP = 8500 WHERE name = 'Jailer_of_Love'       AND groupid =  53;
UPDATE `mob_groups` SET minLevel = 110, maxLevel = 110, HP = 110000, MP = 8500 WHERE name = 'Absolute_Virtue'      AND groupid =  56;

